project_identifier_env: CROWDIN_WARRIORJS_PROJECT_ID
api_key_env: CROWDIN_WARRIORJS_API_KEY
base_path: "../"
preserve_hierarchy: true

files:
  -
    source: '/docs/**/*.md'
    translation: '/website/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'zh-CN': 'zh-CN'
  -
    source: '/website/i18n/en.json'
    translation: '/website/i18n/%locale%.json'
    languages_mapping: *anchor